name: diktat usage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run diktat with a maven plugin
      run: |
        cd maven
        mvn antrun:run@diktat
